### ISSUE TITLE
GCC compiler warnings

### ISSUE THREAD

**Issue by surendarchandra** [01org/isa-l_crypto#1]
Several warnings regarding static functions that are used in non-static functions:
e.g., memclr_sse_fixedlenused(), memcpy_sse_fixedlen() in md5_mb/md5_ctx_sse.c:226, md5_mb/md5_ctx_avx.c:226, md5_mb/md5_ctx_avx2.c:226

Removing all statics from include/memcpy_inline.h fixes these warnings. Thanks

**Comment by gbtucker** [comment]
Chandra, thanks for reporting.  Can you send your environment info?  I don't see the warnings on gcc 5.3, 6.1, clang 3.7, 3.8, and icc 16.0.  Removing static will break Mac builds.

**Comment by surendarchandra** [comment]
I'm on Fedora 22? Here is what gcc thinkks:

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/cloog-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-7) (GCC) 

In file included from sha256_mb/sha256_ctx_sse.c:31:0:
./include/memcpy_inline.h:51:25: warning: 'memclr_sse_fixedlen' is static but used in inline function 'hash_pad' which is not static [enabled by default]
 #define memclr_fixedlen memclr_sse_fixedlen
                         ^
sha256_mb/sha256_ctx_sse.c:227:2: note: in expansion of macro 'memclr_fixedlen'
  memclr_fixedlen(&padblock[i], SHA256_BLOCK_SIZE);
  ^
./include/memcpy_inline.h:48:25: warning: 'memcpy_sse_fixedlen' is static but used in inline function 'hash_init_digest' which is not static [enabled by default]
 #define memcpy_fixedlen memcpy_sse_fixedlen
                         ^
sha256_mb/sha256_ctx_sse.c:220:2: note: in expansion of macro 'memcpy_fixedlen'
  memcpy_fixedlen(digest, hash_initial_digest, sizeof(hash_initial_digest));

Its a warning but we typically treat warnings as errors. Thanks Greg

**Comment by gbtucker** [comment]
Thanks, I'll look into it some more.

**Comment by gbtucker** [comment]
I found that the warning was caused by disagreement between a function prototype as static inline and definition as just inline.  I made the fix and tested on gcc 4.8.2 to confirm it removed the warning.  I will push tomorrow and close the issue.  Thanks again.

**Comment by surendarchandra** [comment]
Thanks, that worked
