### ISSUE TITLE
Get wrong sha256sum when input size is equal or greater than 512MB

### ISSUE THREAD

**Issue by chimucong** [01org/isa-l_crypto#3]
Hello,

I'm trying to calculate the sha256sum of a file, and here is a simple example(please ignore the memory leak) based on [isa-l_crypto/sha256_mb/sha256_mb_test.c](https://github.com/01org/isa-l_crypto/blob/master/sha256_mb/sha256_mb_test.c)

``` c
#include "sha256_mb.h"
#include <stdlib.h>
#include <stdio.h>
#define BUFF_SIZE (1024*1024*64)

#define NUM_JOBS 1

int main() {
    SHA256_HASH_CTX_MGR *mgr = NULL;
    SHA256_HASH_CTX ctxpool[NUM_JOBS];

    posix_memalign((void *) &mgr, 16, sizeof(SHA256_HASH_CTX_MGR));
    sha256_ctx_mgr_init(mgr);
    hash_ctx_init(&ctxpool[0]);


    FILE *f = fopen("path_to_input_file", "r");
    if (f == NULL) {
        printf("can not open file");
        return 0;
    }
    void *buff = malloc(BUFF_SIZE);

    size_t count = 0;
    size_t read_in;

    sha256_ctx_mgr_submit(mgr, &ctxpool[0], buff, 0, HASH_FIRST);
    sha256_ctx_mgr_flush(mgr);
    do {
        read_in = fread(buff, 1, BUFF_SIZE, f);
        sha256_ctx_mgr_submit(mgr, &ctxpool[0], buff, (uint32_t) read_in, HASH_UPDATE);
        sha256_ctx_mgr_flush(mgr);
        count += read_in;
    } while (read_in > 0);

    sha256_ctx_mgr_submit(mgr, &ctxpool[0], buff, 0, HASH_LAST);
    sha256_ctx_mgr_flush(mgr);
    printf("file size:%zu\n", count);

    int j;
    for (j = 0; j < SHA256_DIGEST_NWORDS; j++) {
        printf("%08x ", ctxpool[0].job.result_digest[j]);
    }
    return 0;
}
```

It works well with files that are less than 512MB. But it gets wrong sha256sum when the file size is equal or greater than 512MB.

Is there any problem with my code? (leaving the memory leaking problems alone)

Thanks

**Comment by gbtucker** [comment]
I'll take a look at this thanks.

**Comment by gbtucker** [comment]
You are correct that the maximum total hash size is currently 511MB.  I will push a commit that will increase this to 4095MB.

**Comment by chimucong** [comment]
Thank you very much.
However, I have to deal with large files and 4095MB is not enough for me neither.
As far as I know, the maximum message size of sha256 is 2^64 - 1 bits.
Would you please increase the maximum total hash size to 2^61 - 1 bytes if it's convenient for you.

Thanks again.

**Comment by gbtucker** [comment]
It is possible to extend to 64 bits.  I will add to the feature requests.

**Comment by chimucong** [comment]
Thanks so much for your response, and I really appreciate it.
