### ISSUE TITLE
Incorrect MD5 when data larger then 63 bytes submitted

### ISSUE THREAD

**Issue by ifadams** [01org/isa-l_crypto#4]
Hi,

I've been working with the md5 implementation and I'm not sure if its a bug or if I'm using it incorrectly.

The short version is that if I submit more than 63 bytes, either across multiple submits or a single larger one, when I flush and retrieve the digest the md5 appears incorrect.

If less than 63 bytes, it produces a correct digest.

Thanks!

EDIT: please let me know if example code would be helpful.

**Comment by gbtucker** [comment]
An example would be helpful.  The unit tests choose sizes greater then 63 bytes.  Note that you must submit independent hash jobs until a context is returned for a particular hash, then an update can be submitted.

**Comment by ifadams** [comment]
Below is a hacked together example, so please forgive the horrific conventions and leakiness 

Sounds like I may be doing something wrong as I'm reusing the same hash context across multiple submissions naively, though I'm not sure I quite grasp what to do using multiple contexts...

That said, here's the code to reproduce what I'm talking about....


`
#include <isa-l_crypto/md5_mb.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <inttypes.h>
#include <openssl/md5.h>
#include <string.h>

MD5_HASH_CTX * init_ctx();
MD5_HASH_CTX_MGR * init_mgr();
void md5_update(int first, char *data, int data_size, MD5_HASH_CTX *hash_ctx,
                MD5_HASH_CTX_MGR *hash_mgr);
char * produce_digest(MD5_HASH_CTX *hash_ctx, MD5_HASH_CTX_MGR *hash_mgr);

MD5_HASH_CTX * init_ctx(){

        MD5_HASH_CTX    *hash_ctx;

        hash_ctx = malloc(sizeof(MD5_HASH_CTX));
        hash_ctx_init(hash_ctx);

        return hash_ctx;
}

MD5_HASH_CTX_MGR * init_mgr(){
        MD5_HASH_CTX_MGR        *md5_mgr;

        md5_mgr = malloc(sizeof(MD5_HASH_CTX_MGR));
        md5_ctx_mgr_init(md5_mgr);

        return md5_mgr;
}

void md5_update(int first, char *data, int data_size, MD5_HASH_CTX *hash_ctx,
                MD5_HASH_CTX_MGR *hash_mgr){

        const void * my_buf = (void *) data;
        if(first == 0){
                md5_ctx_mgr_submit(hash_mgr, hash_ctx, my_buf, data_size, HASH_FIRST);
        }else{
                md5_ctx_mgr_submit(hash_mgr, hash_ctx, my_buf, data_size, HASH_UPDATE);
        }

}

char * hex_print(unsigned char * buf){
        int i;
        char *hex_buf = malloc(MD5_DIGEST_LENGTH*2);
        char *append_buf = malloc(4);
        hex_buf[0]='\0';


        for (i = 0; i < MD5_DIGEST_LENGTH; i++){
                sprintf(append_buf,"%02X\0",buf[i]);
                strcat(hex_buf, append_buf);
        }

        free(append_buf);
        return hex_buf;
}

char * produce_digest(MD5_HASH_CTX *hash_ctx, MD5_HASH_CTX_MGR *hash_mgr){

        uint32_t        *digest_buf;
        char            *hex_buf;

        md5_ctx_mgr_submit(hash_mgr, hash_ctx, NULL, 0, HASH_LAST);

        md5_ctx_mgr_flush(hash_mgr);

        digest_buf = hash_ctx_digest(hash_ctx);

        hex_buf = hex_print((unsigned char *)digest_buf);

        return hex_buf;
}



int main(int argc, char **argv){

        int tiny_buf_size = 18;
        char tiny_buf[] = "thisisasmallbuffer";

        int big_buf_size = 64;
        char big_buf[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789012";

        char *hex_buf;

        MD5_HASH_CTX    *ctx_small;
        MD5_HASH_CTX_MGR *mgr_small;
        MD5_HASH_CTX    *ctx_big;
        MD5_HASH_CTX_MGR *mgr_big;

        ctx_small = init_ctx();
        mgr_small = init_mgr();

        md5_update(0, tiny_buf, 18, ctx_small, mgr_small);
        hex_buf = produce_digest(ctx_small, mgr_small);

        printf("Expected Digest: 5182dc880859470653ee39b5b3c662bc\n");
        printf("Small Buf HexDigest: %s\n", hex_buf);


        ctx_big = init_ctx();
        mgr_big = init_mgr();

        md5_update(0, big_buf, 64, ctx_big, mgr_big);
        hex_buf = produce_digest(ctx_big, mgr_big);

        printf("Expected Digest: ca6963a409a0a9866f38b153b9ca872e\n");
        printf("Large Buf HexDigest: %s\n", hex_buf);

        return 0;
}`

**Comment by gbtucker** [comment]
It is because you are not ensuring that your hash_update is complete before issuing your hash_last.  To make your example work you would have to do something like:

```
    while (NULL != md5_ctx_mgr_flush(hash_mgr)) ;
    md5_ctx_mgr_submit(hash_mgr, hash_ctx, NULL, 0, HASH_LAST);
    while (NULL != md5_ctx_mgr_flush(hash_mgr)) ;
```
In produce_digest() and something similar in your _update() function.  This would work but the submit, flush, submit, flush sequence does not take full advantage of the parallelism that is possible if you can keep multiple hash jobs running at once.  A better way would be to keep a context pool and have it resubmit parts of hashes as ctx for a job is returned.

**Comment by ifadams** [comment]
Thanks, fixed the incorrect hash digest issue.

That said,   its targeting an app with isolated, serialized MD5 updates that are themselves a bottleneck, so its not really possible to have multiple distinct hash jobs going at once without a significant re-architecting (we're calling this through a python wrapper)... though I may be misunderstanding what you're saying .

 Is there a way to get some of the speed benefits without repeatedly flushing in a small, single serialized job? Doing so, unsurprisingly, seems to kill the performance to slower than some of the alternative implementations we have access to.

**Comment by gbtucker** [comment]
In order to get the highest performance out of the multi-buffer hashing functions you really need to queue up a few independent hashes.  I don't see why this couldn't be done through a python wrapper but if the hashes really need to be serialized, you don't need standard md5 and you are hashing large buffers ~1K or larger then you might look into other functions like multi-hash.

**Comment by ifadams** [comment]
Yeah, the challenge is more an artifact of the larger architecture than specifically being in python, as well as a huge amount of momentum behind MD5. Sorry for the confusion.  Thanks for your help! Going to close this issue down.
